### ISSUE TITLE
Unable to find tests directory when installed as a module

### ISSUE THREAD

**Issue by andrew-dewitt** [andrew-dewitt/pyspec#4]
With structure like this:

```
andrew@devtest:~/dev/pyspec
.
├── pub_sub
│   ├── events.py
│   └── __init__.py
├── requirements
│   ├── dev.txt
│   └── prod.txt
├── requirements.txt
└── tests
    └── events_spec.py
```

And with `pyspec` installed in environment:

```
andrew@devtest:~/dev/pyspec
$ pyspec
Usage: pyspec [OPTIONS] METHOD MODULE
Try "pyspec --help" for help.

Error: Missing argument "METHOD".
(env)
```

running `pyspec all tests` from project root `./` above, returns this:

```
andrew@devtest:~/dev/pyspec
$ pyspec all tests
Traceback (most recent call last):
  File "/home/andrew/dev/pyspec/env/bin/pyspec", line 11, in <module>
    load_entry_point('pyspec', 'console_scripts', 'pyspec')()
  File "/home/andrew/dev/pyspec/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrew/dev/pyspec/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/andrew/dev/pyspec/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrew/dev/pyspec/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/andrew/dev/pyspec/pyspec/cli/entry.py", line 25, in main
    options[method](module)
  File "/home/andrew/dev/pyspec/pyspec/cli/entry.py", line 15, in all_tests
    run_tests.all_tests(path)
  File "/home/andrew/dev/pyspec/pyspec/cli/run_tests.py", line 6, in all_tests
    test_dir = importlib.import_module(test_dir_str)
  File "/home/andrew/dev/pyspec/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests'
(env)
```

**Comment by andrew-dewitt** [comment]
Adding 

```
import os
print(os.getcwd())
```

to `./pyspec/cli/run_tests.py` at lines 5 & 6 prints the correct `$PWD`:

```
andrew@devtest:~/dev/pyspec
$ pyspec all tests
/home/andrew/dev/pyspec
```

Something must be happening inside `importlib` to change the `$PWD` when calling it like I do at lines 9 & 18, like this: `test_dir = importlib.import_module(test_dir_str)`.
